pid: 0.35
afa: "/home/tc229954/data/prefilter/alignments_and_ddgm/all/*.afa"
afa_directory: "/home/tc229954/data/prefilter/alignments_and_ddgm/all"
out_path_fasta: "/home/tc229954/data/prefilter/clustered/"
domtblout_directory: "/home/tc229954/data/prefilter/pfam/"
fasta_path: "/home/tc229954/data/prefilter/alignments_and_ddgm/all/*train*"
evalue_threshold: 1e-5
augment_threshold: 100
n_emissions: 1000

