pid: 0.5
afas: "/Users/mac/data/prefilter/related_families/afa/*afa"
afa_directory: "/Users/mac/data/prefilter/related_families/afa/"
out_path_fasta: "/Users/mac/data/prefilter/related_families/fasta/"
out_path_json: "/Users/mac/data/prefilter/related_families/json/"
domtblout_directory: "/Users/mac/data/prefilter/pfam/"
evalue_threshold: 1e-5