[package]
name = "post-processing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
pyo3 = "0.15.2"

[lib]
name = "my_lib"
crate-type = ["cdylib"]
