repos:
    - repo: local
      hooks:
          - id: isort
            name: Sort import statements.
            entry: bash -c 'isort "$@"; git add -u' --
            language: python
          - id: black
            name: Black python code formatting
            entry: bash -c 'black "$@"; git add -u' --
            language: python
            types: [python]
