stages:
  train:
    cmd: train
    deps:
    - src
    outs:
    - model_data/best_loss_model.ckpt
  evaluate:
    cmd: evaluate
    deps:
    - src
    - model_data/best_loss_model.ckpt
    outs:
    - results.txt