[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "near"
version = "0.1.0"
requires-python = ">=3.11.11"
dependencies = [
    "numpy",
    "torch",
    "matplotlib",
    "tqdm",
    "pyyaml",
]

[project.scripts]
near = "near.main:main"