model_name:  "ResNet1d"
evaluator_name: "ContrastiveEvaluator"
description: "Use CPU with IVF optimization and multithreading"
index_string: "IVF5000,Flat"
log_verbosity: logging.INFO
checkpoint_path: /xdisk/twheeler/daphnedemekas/prefilter/ResNet1d/23/checkpoints/best_epoch.ckpt
query_file: "data/queries-filtered.fa"
target_file: "data/targets-reversed.fa"
target_embeddings: 'target_embeddings_reversed.pt'
target_names: 'reversed-target-names.txt'
target_lengths: 'reversed-target-lengths.txt'
unrolled_names_file: '/xdisk/twheeler/daphnedemekas/unrolled_names_reversed.txt'
save_dir: "/xdisk/twheeler/daphnedemekas/prefilter-output/CPU-5K-50-masked-reversed"
num_threads: 16
omp_num_threads: 1
device: 'cpu'
index_device: 'cpu'
normalize_embeddings: True
minimum_seq_length: 0
max_seq_length: 512
profiler: False
nprobe: 50
write_results: True
index_path: "/xdisk/twheeler/daphnedemekas/faiss-index-targets-5K-reversed-masked.index"
mask_queries: True 
mask_targets: True
normalise_search_results: False
masked_query_file: data/queries-masked.fa
masked_target_file: data/targets-masked-reversed.fa
