model_name:  "ResNet1d"
evaluator_name: "ContrastiveEvaluator"
description: "Use CPU with IVF optimization and multithreading"
index_string: "IVF20000,Flat"
log_verbosity: logging.INFO
checkpoint_path: /xdisk/twheeler/daphnedemekas/prefilter/ResNet1d/23/checkpoints/best_epoch.ckpt
query_file: "data/evaluationqueries.fa"
target_file: "data/evaluationtargets.fa"
target_embeddings: 'target_embeddings.pt'
target_names: 'target_names.txt'
target_lengths: 'target_lengths.txt'
save_dir: "/xdisk/twheeler/daphnedemekas/prefilter-output/AlignmentEvaluation/del"
num_threads: 16
omp_num_threads: 20
device: 'cpu'
normalize_embeddings: True
minimum_seq_length: 0
max_seq_length: 512
profiler: False
write_results: False
nprobe: 100
output_path: "/xdisk/twheeler/daphnedemekas/prefilter-output/AlignmentEvaluation/del"
evaluator_args:
    encoding_func: None
    model_device: "cpu" 
    index_device: "cpu"
    index_string: "IVF20000,Flat"
    normalize_embeddings: True
    minimum_seq_length: 0
    max_seq_length: 512
    nprobe: 100
    output_path: "/xdisk/twheeler/daphnedemekas/prefilter-output/AlignmentEvaluation/del"
    num_threads: 16
    target_embeddings_path: 'target_embeddings.pt'
