model_name:  "ResNet1d"
evaluator_name: "ContrastiveEvaluator"
description: "Profiler"
index_string: "IVF256,Flat"
log_verbosity: logging.INFO
checkpoint_path: /xdisk/twheeler/daphnedemekas/prefilter/ResNet1d/version_27/checkpoints/epoch_0_2.60146.ckpt
query_file: "data/evaluationqueries.fa"
target_file: "data/evaluationtargets.fa"
target_embeddings: 'target_embeddings_v27-3.pt'
target_names: 'target_embeddings_v27-3_names.pickle'
target_lengths: 'target_embeddings_v27-3_lengths.pickle'
save_dir: "/xdisk/twheeler/daphnedemekas/prefilter-output/AlignmentEvaluation/v273-5"
num_threads: 1
device: 'cpu'
nprobe: 5
normalize_embeddings: True
minimum_seq_length: 0
max_seq_length: 512
profiler: True