model_name:  "ResNet1d"
evaluator_name: "ContrastiveEvaluator"
description: "Use CPU with IVF optimization and multithreading"
log_verbosity: logging.INFO
checkpoint_path: "/xdisk/twheeler/daphnedemekas/prefilter/ResNet1d/version_53/checkpoints/epoch_4_2.57257.ckpt"
query_file: "data/evaluationqueries.fa"
target_file: "data/evaluationtargets.fa"
target_embeddings: 'target_embeddings_new.pt'
target_names: 'target_names.txt'
target_lengths: 'target_lengths.txt'
num_threads: 1
omp_num_threads: 4
profiler: False
device: "cuda"
evaluator_args:
    encoding_func: None
    model_device: "cuda" 
    index_device: "cuda"
    index_string: "IVF20000,PQ32"  # IVF256,PQ16", #IVF256
    normalize_embeddings: True
    minimum_seq_length: 0
    max_seq_length: 512
    nprobe: 50
    output_path: "/xdisk/twheeler/daphnedemekas/prefilter-output/AlignmentEvaluation/new-checkpoint-gpu"
    num_threads: 1
    target_embeddings_path: 'target_embeddings_new.pt'
    
