model_name:  "ResNet1d"
evaluator_name: "ContrastiveEvaluator"
description: "Use CPU with IVF optimization and multithreading"
index_string: "IVF256,Flat"
log_verbosity: logging.INFO
checkpoint_path: /xdisk/twheeler/daphnedemekas/prefilter/ResNet1d/23/checkpoints/best_epoch.ckpt
query_file: "data/evaluationqueries.fa"
target_file: "data/evaluationtargets.fa"
target_embeddings: 'targets_2000.pt'
target_names: 'targetnames2000.pickle'
target_lengths: 'target_lengths_2000.pickle'
save_dir: "/xdisk/twheeler/daphnedemekas/prefilter-output/AlignmentEvaluation/IVF-5"
num_threads: 16
device: 'cpu'
nprobe: 5
normalize_embeddings: True
minimum_seq_length: 0
max_seq_length: 2000
evaluator_args:
    query_file: "data/evaluationqueries.fa"
    encoding_func: None
    model_device: "cpu" 
    index_device: "cpu"
    index_string: "IVF256,Flat"  # IVF256,PQ16", #IVF256
    nprobe: 5
    normalize_embeddings: True
    minimum_seq_length: 0
    max_seq_length: 2000
    output_path: "/xdisk/twheeler/daphnedemekas/prefilter-output/AlignmentEvaluation/IVF-5"
    num_threads: 16
