model_name:  "ResNet1d"
evaluator_name: "ContrastiveEvaluator"
description: "Use CPU with IVF optimization and multithreading"
index_sring: "IVF256,Flat"
log_verbosity: logging.INFO
checkpoint_path: /xdisk/twheeler/daphnedemekas/prefilter/ResNet1d/version_25/checkpoints/epoch_4_2.86923.ckpt
query_file: "data/evaluationqueries.fa"
target_embeddings: 'target_embeddings.pt'
target_names: target_names.txt
target_lengths: target_lengths.txt
num_threads: 1
device: "cuda"
evaluator_args:
    encoding_func: None
    model_device: "cuda" 
    index_device: "cuda"
    index_string: "IVF256,Flat"  # IVF256,PQ16", #IVF256
    nprobe: 10
    normalize_embeddings: True
    minimum_seq_length: 0
    max_seq_length: 2000
    output_path: "/xdisk/twheeler/daphnedemekas/prefilter-output/AlignmentEvaluation/IVF-10-new-real"
    num_threads: 1

