model_name:  "ResNet1d"
evaluator_name: "ContrastiveEvaluator"
description: "Use CPU with IVF optimization and multithreading"
index_string: "IVF5000,PQ32"
log_verbosity: logging.INFO
checkpoint_path: /xdisk/twheeler/daphnedemekas/prefilter/ResNet1d/23/checkpoints/best_epoch.ckpt
query_file: "data/queries-test.fa"
target_file: "data/targets-filtered.fa"
target_embeddings: 'target_embeddings.pt'
target_names: 'target_names.txt'
target_lengths: 'target_lengths.txt'
save_dir: "/xdisk/twheeler/daphnedemekas/prefilter-output/CPU-20K-50-rust"
num_threads: 1
omp_num_threads: 1
device: 'cuda'
normalize_embeddings: True
minimum_seq_length: 0
max_seq_length: 512
profiler: False
nprobe: 70
write_results: True
index_path: "/xdisk/twheeler/daphnedemekas/faiss-index-targets-5K-gpu.index"
scores_path: "/xdisk/twheeler/daphnedemekas/all-scores-5K-70-gpu.h5"
indices_path:  "/xdisk/twheeler/daphnedemekas/all-indices-5K-70-gpu.h5"
query_names_path:  "/xdisk/twheeler/daphnedemekas/query-names-5K-70-gpu.txt"
