model_name:  "ResNet1d"
evaluator_name: "ContrastiveEvaluator"
description: "Use CPU with IVF optimization and multithreading"
index_string: "IVF256,Flat"
log_verbosity: logging.INFO
checkpoint_path: /xdisk/twheeler/daphnedemekas/prefilter/SCL_test.ckpt
query_file: "data/evaluationqueries.fa"
target_file: "data/evaluationtargets.fa"
target_embeddings: 'target_embeddings_SCL.pt'
target_names: 'target_embeddings_SCL_names.pickle'
target_lengths: 'target_embeddings_SCL_lengths.pickle'
save_dir: "/xdisk/twheeler/daphnedemekas/prefilter-output/AlignmentEvaluation/SCL_10"
num_threads: 16
device: 'cpu'
nprobe: 10
normalize_embeddings: True
minimum_seq_length: 0
max_seq_length: 512