description: ("Training with supervised contrastive loss, multiple postiives, and indels")
model_name:  "ResNet1dMultiPos"
dataset_name: "AlignmentGeneratorIndelsMultiPos"
log_dir: "/home/daphnedemekas/prefilter"
log_verbosity: logging.INFO
seed: 42

model_args:
    learning_rate: 0.0005
    log_interval: 3000
    indels: True
    res_block_n_filters: 256
    res_block_kernel_size: 3
    in_channels: 20
    n_res_blocks: 8
    padding: "same"
    padding_mode: "circular"


train_dataset_args:
    ali_path: "/home/daphnedemekas/data/trainpathsmultipos.txt"
    seq_len: 128

dataloader_args:
    batch_size: 8
    num_workers: 6
    drop_last: True

trainer_args:
    accelerator: "gpu"
    num_nodes: 1
    max_epochs: 100

val_dataset_args:
    ali_path: "/home/daphnedemekas/data/valpathsmultipos.txt"
    seq_len: 128
    training: False
