description: "Training on alignment data with indels using real sequence padding and masked regloss"
model_name:  "ResNet1d"
dataset_name: "AlignmentGeneratorWithIndels"
log_dir: "/xdisk/twheeler/daphnedemekas/prefilter"
log_verbosity: logging.INFO
seed: 42

model_args:
    learning_rate: 0.001
    log_interval: 5000
    in_channels: 20
    indels: True
    res_block_n_filters: 256
    res_block_kernel_size: 3
    n_res_blocks: 8
    padding: "same"
    padding_mode: "circular"

train_dataset_args:
    ali_path: "/xdisk/twheeler/daphnedemekas/train_paths-final.txt"
    seq_len: 128

dataloader_args:
    batch_size: 64
    num_workers: 6
    drop_last: True

trainer_args:
    accelerator: "gpu"
    num_nodes: 1
    max_epochs: 100

val_dataset_args:
    ali_path: "/xdisk/twheeler/daphnedemekas/valpaths-final.txt"
    seq_len: 128
    training: False