description: "Training on alignment data with indels using real sequence padding and masked regloss"
model_name:  "ResNet1d"
dataset_name: "AlignmentGeneratorWithIndels"
log_dir: "/xdisk/twheeler/daphnedemekas/prefilter"
log_verbosity: logging.INFO
seed: 144272510
checkpoint: "/xdisk/twheeler/daphnedemekas/prefilter/ResNet1d/version_52/checkpoints/epoch_1_2.90632.ckpt"
model_args:
    learning_rate: 0.000001
    log_interval: 100000
    in_channels: 20
    indels: True
    res_block_n_filters: 256
    res_block_kernel_size: 7
    n_res_blocks: 8
    padding: "same"
    padding_mode: "zeros"

train_dataset_args:
    ali_path: "/xdisk/twheeler/daphnedemekas/trainseqs.txt"
    seq_len: 256

dataloader_args:
    batch_size: 64
    num_workers: 12
    drop_last: True

trainer_args:
    accelerator: "gpu"
    num_nodes: 1
<<<<<<< HEAD
    max_epochs: 2
=======
    max_epochs: 100
>>>>>>> feb16feb3b82bc4c09ec95cf5a97e4b4ee5069f2
    precision: 16

val_dataset_args:
    ali_path: "/xdisk/twheeler/daphnedemekas/evalseqs.txt"
    seq_len: 128
    training: False
