description: ("Training with supervised contrastive loss, multiple postiives, and indels")
model_name:  "ResNet1dMultiPos"
dataset_name: "AlignmentGeneratorIndelsMultiPos"
log_dir: "/xdisk/twheeler/daphnedemekas/prefilter"
log_verbosity: logging.INFO
seed: 42

model_args:
    learning_rate: 0.00001
    log_interval: 1000
    in_channels: 20
    indels: True

train_dataset_args:
    ali_path: "/xdisk/twheeler/daphnedemekas/train_paths-multipos.txt"
    seq_len: 128

dataloader_args:
    batch_size: 16
    num_workers: 6
    drop_last: True

trainer_args:
    accelerator: "gpu"
    num_nodes: 1
    max_epochs: 100

val_dataset_args:
    ali_path: "/xdisk/twheeler/daphnedemekas/valpathsmultipos.txt"
    seq_len: 128
    training: False