# -*- coding: utf-8 -*-
"""tcolligan0 Pfam 32.0 seed models inference example colab

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15G9gAUZkQbSZekg7yHMBvx4wEqQHQObL

# This code is intended to support the publication "Using Deep Learning to Annotate the Protein Universe".
[preprint link](https://doi.org/10.1101/626507)

**Note**: The easiest way to use this notebook is as a colab notebook, which allows you to dive in with no setup. We recommend you enable a free GPU by going:

> **Runtime**   →   **Change runtime type**   →   **Hardware Accelerator: GPU**
"""

# Commented out IPython magic to ensure Python compatibility.
# !git clone https://github.com/google-research/proteinfer
# %cd proteinfer
# !pip3 install -qr  requirements.txt

import json

import numpy as np

import inference

# Get a savedmodel
# !wget -qN https://storage.googleapis.com/brain-genomics-public/research/proteins/pfam/models/single_domain_per_sequence_zipped_models/seed_random_32.0/5356760.tar.gz
# unzip
# !tar xzf 5356760.tar.gz
# Get the vocabulary for the savedmodel, which tells you which output index means which family
# !wget https://storage.googleapis.com/brain-genomics-public/research/proteins/pfam/models/single_domain_per_sequence_zipped_models/trained_model_pfam_32.0_vocab.json

# Find the unzipped path
# !ls *5356760*

# Load savedmodel
inferrer = inference.Inferrer(
    'trn-_cnn_random__random_sp_gpu-cnn_for_random_pfam-5356760', use_tqdm=True, batch_size=32,
    activation_type="confidences"
)
# Load vocab
with open('trained_model_pfam_32.0_vocab.json') as f:
    vocab = json.loads(f.read())

# Run inference
hemoglobin = 'MVLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHFDLSHGSAQVKGHGKKVADALTNAVAHVDDMPNALSALSDLHAHKLRVDPVNFKLLSHCLLVTLAAHLPAEFTPAVHASLDKFLASVSTVLTSKYR'
globin_domain = hemoglobin[6:107]  # 0-indexed, right inclusive because of the way slices in python work
activations = inferrer.get_activations([globin_domain])

# Find what the most likely class is
print(np.argmax(activations))

vocab[8505]  # PF00042 is family Globin
